repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: .*drawio$
  - id: check-yaml
    args: [--allow-multiple-documents]
    additional_dependencies: [ruamel.yaml]
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-vcs-permalinks
  - id: debug-statements
  - id: detect-private-key
  - id: forbid-new-submodules
  - id: mixed-line-ending
    args: [--fix, lf]
  - id: check-toml
  - id: check-json
    exclude: ^.devcontainer/
  - id: pretty-format-json
    args: [--autofix]
    exclude: ^.*appsettings.*\.json$

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.81.0
  hooks:
  - id: terraform_fmt
  - id: terragrunt_fmt

- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.11
  hooks:
  - id: pymarkdown
    additional_dependencies: [wcwidth]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
    additional_dependencies: [ruamel_yaml]

- repo: https://github.com/kamadorueda/alejandra
  # TODO: When this issue is resolved, switch to proper tag ref
  # Ref: https://github.com/kamadorueda/alejandra/issues/388
  rev: e53c2c6c6c103dc3f848dbd9fbd93ee7c69c109f
  hooks:
  - id: alejandra-nix

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.26.3
  hooks:
  - id: check-renovate
    additional_dependencies: [json5]
  - id: check-github-actions

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
  - id: hadolint
- repo: local
  hooks:
  - id: copy-repeated-files
    name: Copy files
    # entry: "/usr/bin/find . -maxdepth 1 -type d -not -path '*/.*' -not -path '.'  | xargs -I% cp .envrc %"
    entry: copy-repeated-files.sh
    language: script
    always_run: true
    pass_filenames: false
