repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.81.0
  hooks:
  - id: terraform_fmt
  - id: terragrunt_fmt

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-added-large-files
  - id: check-toml
  - id: detect-private-key
  - id: forbid-new-submodules
  - id: mixed-line-ending
    args: [--fix, lf]
  - id: check-json
    exclude: ^.devcontainer/
  - id: pretty-format-json
    args: [--autofix]

- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.11
  hooks:
  - id: pymarkdown

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

