name: Update chores

on:
  # Allow manual triggers.
  workflow_dispatch:

  # Automatically run twice a month
  schedule:
  - cron: 0 7 1,15 * MON

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: Apakottur/action-poetry-package-update@v1
      with:
        base-branch: main
        poetry-version: 1.7.1
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: vrslev/pre-commit-autoupdate@v1.0.0
    - uses: pre-commit-ci/lite-action@v1.0.1
      if: always()
    - uses: peter-evans/create-pull-request@v5
      with:
        branch: pre-commit-autoupdate
        title: 'chore(deps): Update pre-commit hooks'
        commit-message: 'chore(deps): Update pre-commit hooks'
        body: Update pre-commit hooks
        labels: dependencies
        token: ${{ secrets.WRITEBACK_TOKEN }}
        delete-branch: true
        committer: Ariel Richtman <Ariel.Richtman@SilverRailTech.com>
        author: Ariel Richtman <Ariel.Richtman@SilverRailTech.com>
