name: Update chores

on:
  # Allow manual triggers.
  workflow_dispatch:

  # Automatically run twice a month
  schedule:
  - cron: 0 7 1,15 * MON

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Update stuff
      run: |
        nix flake update
        nix develop --command pre-commit autoupdate
        nix develop --command poetry update
    - uses: peter-evans/create-pull-request@v6
      with:
        branch: auto-updates
        token: ${{ secrets.WRITEBACK_TOKEN }}
        title: 'chore(deps): Update packages'
        commit-message: 'chore(deps): Update packages'
        body: Update packages
        labels: dependencies
        delete-branch: true
        committer: Richtman, Ariel <Ariel.Richtman@SilverRailTech.com>
        author: Richtman, Ariel <Ariel.Richtman@SilverRailTech.com>
